### ISSUE TITLE
hello, some questions about the simulator

### ISSUE THREAD

**Issue by schietau** [MLJejuCamp2017/DRL_based_SelfDrivingCarControl#12]
thanks for providing the DRL algorithm and the unity environment. i doubt how the agent(self-driving car) in the unity environment communicate with other vehicles, how the self-driving car' state transform, and how the reward  define  in the the code of unity environment. Because unity environment is a  executable program, we can't know the detail information, is there some reference material for the detail information about the internal code of unity environment .thanks very much!

**Comment by Kyushik** [comment]
Hello. Thanks for using my simulator! 
The agent doesn't communicate with other vehicles. It just get front camera image and sensor data, which is implemented by ray cast in Unity. 
Information about the state, action and reward is in the readme.md. 
I want to make variables changeable. 
I will update about this at some day. 
I cannot upload all the Unity code, because the 3D models are paid one.
But I can upload the C# code about the agent.

**Comment by schietau** [comment]
> Hello. Thanks for using my simulator!
> The agent doesn't communicate with other vehicles. It just get front camera image and sensor data, which is implemented by ray cast in Unity.
> Information about the state, action and reward is in the readme.md.
> I want to make variables changeable.
> I will update about this at some day.
> I cannot upload all the Unity code, because the 3D models are paid one.
> B

**Comment by schietau** [comment]
it's very nice of you. thanks for your answer.
